### ISSUE TITLE
The conflict in 2.3.2

### ISSUE THREAD

**Issue by Marabar** [bertoost/MODX-Polls#42]
In Russian, there is a conflict after clearing the cache. In the English version of the manager - no problem.

![kazam_screenshot_00017](https://cloud.githubusercontent.com/assets/9001228/5410056/b4766a40-8212-11e4-8dcb-31b9b5278a8b.png)

Do not shut down function
https://github.com/bertoost/MODX-Polls/blob/master/core/components/polls/model/polls/request/pollsconnectorrequest.class.php#L11

**Comment by tartakxg** [comment]
do you have answer how fix this problem?

**Comment by idimko** [comment]
to fix this problem, you need to convert all php files in `/core/components/polls/lexicon/ru` into UTF8 (without BOM)

**Comment by solidusite** [comment]
fixed in #48
